Fix SystemUI for dagger 2.47
Dagger 2.47 has envorced a requirement that modules cannot be private
(b/283273372).  This causes errors when compiling SystemUI, for example

com/android/systemui/statusbar/notification/collection/PrivateModule.java:14: error: Modules cannot be private.
abstract interface PrivateModule {
                   ^

Make the failing modules public.

Bug: 293884229
Test: m SystemUI
Change-Id: I1d8e7bd2ad40389a26082b353ab9574b1bbdd50f